package com.glassvpn.app.ui.theme

data class AppStrings(
    val appName: String,
    val home: String,
    val servers: String,
    val settings: String,
    val tapToConnect: String,
    val tapToDisconnect: String,
    val connecting: String,
    val connected: String,
    val disconnected: String,
    val currentServer: String,
    val noServerSelected: String,
    val selectServer: String,
    val fastest: String,
    val ping: String,
    val sessions: String,
    val speed: String,
    val language: String,
    val english: String,
    val myanmar: String,
    val about: String,
    val aboutText: String,
    val refreshServers: String,
    val loadingServers: String,
    val noServers: String,
    val vpnPermissionTitle: String,
    val vpnPermissionText: String,
    val allow: String,
    val cancel: String,
    val connectedTo: String,
    val disconnectedFrom: String,
    val failedToConnect: String,
    val retry: String,
    val checkForUpdates: String,
    val checkingForUpdates: String,
    val upToDate: String,
    val updateAvailable: String,
    val downloadAndInstall: String,
    val downloading: String,
    val downloadFailed: String,
    val diagnostics: String,
    val diagnosticsDesc: String,
    val exportDiagnostics: String,
    val diagnosticsSaved: String,
    val diagnosticsFailed: String,
    val version: String,
)

val EnStrings = AppStrings(
    appName = "GlassVPN",
    home = "Home",
    servers = "Servers",
    settings = "Settings",
    tapToConnect = "Tap to connect",
    tapToDisconnect = "Tap to disconnect",
    connecting = "Connecting…",
    connected = "Connected",
    disconnected = "Disconnected",
    currentServer = "Current server",
    noServerSelected = "No server selected",
    selectServer = "Select server",
    fastest = "Fastest",
    ping = "Ping",
    sessions = "Sessions",
    speed = "Speed",
    language = "Language",
    english = "English",
    myanmar = "မြန်မာ",
    about = "About",
    aboutText = "GlassVPN — free VPN with iOS Liquid Glass design.\nServers via VPNGate public relays.",
    refreshServers = "Refresh",
    loadingServers = "Loading servers…",
    noServers = "No servers found. Pull to refresh.",
    vpnPermissionTitle = "VPN Permission",
    vpnPermissionText = "GlassVPN needs permission to create a VPN connection.",
    allow = "Allow",
    cancel = "Cancel",
    connectedTo = "Connected to",
    disconnectedFrom = "Disconnected",
    failedToConnect = "Connection failed",
    retry = "Retry",
    checkForUpdates = "Check for Updates",
    checkingForUpdates = "Checking…",
    upToDate = "You're up to date",
    updateAvailable = "Update available",
    downloadAndInstall = "Download & Install",
    downloading = "Downloading…",
    downloadFailed = "Download failed. Try again.",
    diagnostics = "Diagnostics",
    diagnosticsDesc = "Find problems and export a report",
    exportDiagnostics = "Export diagnostic report (.txt)",
    diagnosticsSaved = "Report saved to Downloads",
    diagnosticsFailed = "Could not save report",
    version = "Version",
)

val MmStrings = AppStrings(
    appName = "GlassVPN",
    home = "ပင်မ",
    servers = "ဆာဗာများ",
    settings = "ဆက်တင်",
    tapToConnect = "ချိတ်ဆက်ရန် နှိပ်ပါ",
    tapToDisconnect = "ဖြုတ်ရန် နှိပ်ပါ",
    connecting = "ချိတ်ဆက်နေသည်…",
    connected = "ချိတ်ဆက်ပြီး",
    disconnected = "ချိတ်ဆက်မထားပါ",
    currentServer = "လက်ရှိဆာဗာ",
    noServerSelected = "ဆာဗာ မရွေးထားပါ",
    selectServer = "ဆာဗာရွေးပါ",
    fastest = "အမြန်ဆုံး",
    ping = "Ping",
    sessions = "အသုံးပြုသူ",
    speed = "အမြန်နှုန်း",
    language = "ဘာသာစကား",
    english = "English",
    myanmar = "မြန်မာ",
    about = "အကြောင်း",
    aboutText = "GlassVPN — iOS Liquid Glass ဒီဇိုင်းနဲ့ free VPN။\nVPNGate public relay ဆာဗာများ သုံးထားသည်။",
    refreshServers = "ပြန်ရယူ",
    loadingServers = "ဆာဗာများ ရယူနေသည်…",
    noServers = "ဆာဗာ မတွေ့ပါ။ ပြန်ရယူကြည့်ပါ။",
    vpnPermissionTitle = "VPN ခွင့်ပြုချက်",
    vpnPermissionText = "VPN ချိတ်ဆက်မှု ဖန်တီးဖို့ GlassVPN က ခွင့်ပြုချက် လိုပါတယ်။",
    allow = "ခွင့်ပြုမယ်",
    cancel = "မလုပ်ဘူး",
    connectedTo = "ချိတ်ဆက်ပြီး",
    disconnectedFrom = "ဖြုတ်လိုက်ပြီ",
    failedToConnect = "ချိတ်ဆက်မှု မအောင်မြင်ပါ",
    retry = "ထပ်ကြိုးစား",
    checkForUpdates = "အပ်ဒိတ် စစ်ဆေးရန်",
    checkingForUpdates = "စစ်ဆေးနေသည်…",
    upToDate = "နောက်ဆုံးဗားရှင်း ဖြစ်နေပါပြီ",
    updateAvailable = "အပ်ဒိတ် ရရှိနိုင်ပါသည်",
    downloadAndInstall = "ဒေါင်းလုဒ်ဆွဲပြီး ထည့်သွင်းရန်",
    downloading = "ဒေါင်းလုဒ်ဆွဲနေသည်…",
    downloadFailed = "ဒေါင်းလုဒ် မအောင်မြင်ပါ။ ထပ်ကြိုးစားပါ။",
    diagnostics = "ပြဿနာရှာဖွေရေး",
    diagnosticsDesc = "ပြဿနာရှာပြီး အစီရင်ခံစာ ထုတ်ရန်",
    exportDiagnostics = "အစီရင်ခံစာ ထုတ်ရန် (.txt)",
    diagnosticsSaved = "Downloads ထဲသို့ သိမ်းပြီးပါပြီ",
    diagnosticsFailed = "သိမ်း၍ မရပါ",
    version = "ဗားရှင်း",
)

fun stringsFor(lang: String): AppStrings = if (lang == "my") MmStrings else EnStrings

fun countryFlag(code: String): String = when (code) {
    "SG" -> "🇸🇬"
    "TH" -> "🇹🇭"
    "MY" -> "🇲🇾"
    "JP" -> "🇯🇵"
    "US" -> "🇺🇸"
    "PH" -> "🇵🇭"
    "MM" -> "🇲🇲"
    else -> "🌐"
}
